module.exports = [
  require('./home'),
  require('./static'),
  require('./seeker_step1'),
  require('./seeker_step2'),
  require('./results'),
  require('./getUsers'),
  require('./detailedResults'),
  require('./registration'),
  require('./thankyou'),
  require('./signup'),
  require('./facebooklogin'),
  require('./fileUpload'),
  require('./sign-s3'),
  require('./redirect_results'),
  require('./postcode'),
];
